### ISSUE TITLE
100% chance that storage's memory mode will result in SQLITE_LOCKED

### ISSUE THREAD

**Issue by Jhonfunk** [anacrolix/squirrel#2]
```golang

	cacheOpts := squirrel.NewCacheOpts{
		NewConnOpts: squirrel.NewConnOpts{
			Memory: true,
			Path:   ":memory:",
		},
	}

...

func (c *torrent.Client) video(w http.ResponseWriter, r *http.Request) {

	f := c.Torrents()[0].Files()[0].NewReader()

	http.ServeContent(w, r, "test", time.Now(), f)
}

http.HandleFunc("/video", c.video)
````

Then play it using the mpv, and when the mpv does a couple of seek operations, an error occurs. The probability of error is 100%, which makes memory mode almost unusable.

```bash

[ERR github.com/anacrolix/torrent peer.go:724]
  *torrent.PeerConn 0xc001450a88: writing received chunk 678: sqlite.Stmt.Step(Wait): SQLITE_LOCKED: database is deadlocked (
                        update keys
                        set
                                last_used=cast(unixepoch('subsec')*1e3 as integer),
                                access_count=access_count+1
                        where key_id=?) <*torrent.Client 0xc00017f908>
[CRT github.com/anacrolix/torrent torrent.go:2761]
  default chunk write error handler: disabling data download <*torrent.Client 0xc00017f908>
[WRN hashing github.com/anacrolix/torrent torrent.go:2588]
  error hashing piece 4: sqlite.Stmt.Step(Wait): SQLITE_LOCKED: database is deadlocked (
                        update keys
                        set
                                last_used=cast(unixepoch('subsec')*1e3 as integer),
                                access_count=access_count+1
                        where key_id=?) <*torrent.Client 0xc00017f908>

```

**Comment by anacrolix** [comment]
Thanks for the report. The memory mode has received very little testing or use recently. I believe I did some work to provide some APIs that don't allow for deadlocking if you use a sqlite VFS that doesn't allow concurrent readers, it's likely that the code in anacrolix/torrent can be checked to ensure it's not using the older APIs/methods.

I don't really want to spend time to fix the memory-only use of sqlite, but I do welcome patches if you are keen on it. The performance was 3-4x the disk performance for obvious reasons, but it didn't satisfy the requirements I had which was actually storing on disk and exceeding memory.

I recommend https://github.com/anacrolix/possum instead (all storage drivers are available in anacrolix/torrent for this) if you are happy to store on disk, it significantly outperforms anacrolix/squirrel on disk.

**Comment by Jhonfunk** [comment]
@anacrolix

[possum ]( https://github.com/anacrolix/possum)is great. But I do need a fully in-memory storage, and it looks like I'll just have to try to implement a simple in-memory stroage myself. and would very much like to see you gradually replace each part of  [torrent ]( https://github.com/anacrolix/torrent) with the rust implementation.

**Comment by anacrolix** [comment]
Do keep in mind it's not much work to fix the deadlocks in squirrel, I've just chased better performance in the other modes and left it unloved.
